import Head from 'next/head'
import Nav from '../components/nav'
import { Input, Textarea } from '../components/forms'
import Button from '../components/buttons'
import { useContext, useState } from 'react'
import { ItemsContext } from '../context/items'

export default function Create() {
  const { addItem } = useContext(ItemsContext);
  const [formValue, setFormValue] = useState({
    brand: '',
    title: '',
    description: '',
    mechanics: '',
    terms: '',
    email: null,
  })

  const onCreate = (e) => {
    console.log(e)
    // addItem(formValue, (item) => {
    //   setSubmitting(false)
    // });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <main className='container mx-auto max-w-5xl px-4'>
        <div className="form-control w-full mb-2">
          <h1 className='text-2xl pt-10 pb-4'>
            New Promo
          </h1>
          <div className='mb-6'>
            <label className="label">
              <span className="label-text">Brand Name</span>
            </label>
            <Input type="text" placeholder="Type here" className="input input-bordered w-full" />
          </div>
          <div className='mb-6'>
            <label className="label">
              <span className="label-text">Promo title</span>
            </label>
            <Input type="text" placeholder="Type here" className="input input-bordered w-full" />
          </div>
          <div className='mb-6'>
            <label className="label">
              <span className="label-text">Promo Description</span>
            </label>
            <Textarea type="text" placeholder="Type here" className="textarea textarea-bordered w-full"/>
          </div>
          <div className='mb-6'>
            <label className="label">
              <span className="label-text">Promo Mechanics</span>
            </label>
            <Textarea type="text" placeholder="Type here" className="textarea textarea-bordered w-full" rows={10} />
          </div>
          <div className='mb-6'>
            <label className="label">
              <span className="label-text">Terms and Conditions</span>
            </label>
            <Textarea type="text" placeholder="Type here" className="textarea textarea-bordered w-full" rows={10} />
          </div>
          <div className='mb-6'>
            <Button block primary onClick={onCreate}>Create</Button>
          </div>
        </div>
      </main>
    </>
  )
}
